/**
 * loopback4-example-shopping
 * LoopBack 4 Example: Online Shopping APIs
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: dev@loopback.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KeyAndPassword model module.
 * @module model/KeyAndPassword
 * @version 1.1.1
 */
class KeyAndPassword {
    /**
     * Constructs a new <code>KeyAndPassword</code>.
     * @alias module:model/KeyAndPassword
     */
    constructor() { 
        
        KeyAndPassword.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KeyAndPassword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KeyAndPassword} obj Optional instance to populate.
     * @return {module:model/KeyAndPassword} The populated <code>KeyAndPassword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KeyAndPassword();

            if (data.hasOwnProperty('resetKey')) {
                obj['resetKey'] = ApiClient.convertToType(data['resetKey'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('confirmPassword')) {
                obj['confirmPassword'] = ApiClient.convertToType(data['confirmPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} resetKey
 */
KeyAndPassword.prototype['resetKey'] = undefined;

/**
 * @member {String} password
 */
KeyAndPassword.prototype['password'] = undefined;

/**
 * @member {String} confirmPassword
 */
KeyAndPassword.prototype['confirmPassword'] = undefined;






export default KeyAndPassword;

