/**
 * loopback4-example-shopping
 * LoopBack 4 Example: Online Shopping APIs
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: dev@loopback.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewUser model module.
 * @module model/NewUser
 * @version 1.1.1
 */
class NewUser {
    /**
     * Constructs a new <code>NewUser</code>.
     * (tsType: NewUserRequest, schemaOptions: { title: &#39;NewUser&#39; })
     * @alias module:model/NewUser
     * @param email {String} 
     * @param password {String} 
     */
    constructor(email, password) { 
        
        NewUser.initialize(this, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password) { 
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>NewUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewUser} obj Optional instance to populate.
     * @return {module:model/NewUser} The populated <code>NewUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
            }
            if (data.hasOwnProperty('resetKey')) {
                obj['resetKey'] = ApiClient.convertToType(data['resetKey'], 'String');
            }
            if (data.hasOwnProperty('resetCount')) {
                obj['resetCount'] = ApiClient.convertToType(data['resetCount'], 'Number');
            }
            if (data.hasOwnProperty('resetTimestamp')) {
                obj['resetTimestamp'] = ApiClient.convertToType(data['resetTimestamp'], 'String');
            }
            if (data.hasOwnProperty('resetKeyTimestamp')) {
                obj['resetKeyTimestamp'] = ApiClient.convertToType(data['resetKeyTimestamp'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
NewUser.prototype['id'] = undefined;

/**
 * @member {String} email
 */
NewUser.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
NewUser.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
NewUser.prototype['lastName'] = undefined;

/**
 * @member {Array.<String>} roles
 */
NewUser.prototype['roles'] = undefined;

/**
 * @member {String} resetKey
 */
NewUser.prototype['resetKey'] = undefined;

/**
 * @member {Number} resetCount
 */
NewUser.prototype['resetCount'] = undefined;

/**
 * @member {String} resetTimestamp
 */
NewUser.prototype['resetTimestamp'] = undefined;

/**
 * @member {String} resetKeyTimestamp
 */
NewUser.prototype['resetKeyTimestamp'] = undefined;

/**
 * @member {String} password
 */
NewUser.prototype['password'] = undefined;






export default NewUser;

