/**
 * loopback4-example-shopping
 * LoopBack 4 Example: Online Shopping APIs
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: dev@loopback.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderScopeFilter from './OrderScopeFilter';

/**
 * The OrderIncludeFilterItems model module.
 * @module model/OrderIncludeFilterItems
 * @version 1.1.1
 */
class OrderIncludeFilterItems {
    /**
     * Constructs a new <code>OrderIncludeFilterItems</code>.
     * @alias module:model/OrderIncludeFilterItems
     */
    constructor() { 
        
        OrderIncludeFilterItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderIncludeFilterItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderIncludeFilterItems} obj Optional instance to populate.
     * @return {module:model/OrderIncludeFilterItems} The populated <code>OrderIncludeFilterItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderIncludeFilterItems();

            if (data.hasOwnProperty('relation')) {
                obj['relation'] = ApiClient.convertToType(data['relation'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = OrderScopeFilter.constructFromObject(data['scope']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} relation
 */
OrderIncludeFilterItems.prototype['relation'] = undefined;

/**
 * @member {module:model/OrderScopeFilter} scope
 */
OrderIncludeFilterItems.prototype['scope'] = undefined;






export default OrderIncludeFilterItems;

