/**
 * loopback4-example-shopping
 * LoopBack 4 Example: Online Shopping APIs
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: dev@loopback.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfobjectset from './OneOfobjectset';
import OneOfstringarray from './OneOfstringarray';

/**
 * The ProductFilter model module.
 * @module model/ProductFilter
 * @version 1.1.1
 */
class ProductFilter {
    /**
     * Constructs a new <code>ProductFilter</code>.
     * @alias module:model/ProductFilter
     */
    constructor() { 
        
        ProductFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductFilter} obj Optional instance to populate.
     * @return {module:model/ProductFilter} The populated <code>ProductFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductFilter();

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], OneOfstringarray);
            }
            if (data.hasOwnProperty('where')) {
                obj['where'] = ApiClient.convertToType(data['where'], {'String': Object});
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], OneOfobjectset);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} offset
 */
ProductFilter.prototype['offset'] = undefined;

/**
 * @member {Number} limit
 */
ProductFilter.prototype['limit'] = undefined;

/**
 * @member {Number} skip
 */
ProductFilter.prototype['skip'] = undefined;

/**
 * @member {module:model/OneOfstringarray} order
 */
ProductFilter.prototype['order'] = undefined;

/**
 * @member {Object.<String, Object>} where
 */
ProductFilter.prototype['where'] = undefined;

/**
 * @member {module:model/OneOfobjectset} fields
 */
ProductFilter.prototype['fields'] = undefined;






export default ProductFilter;

